fileVersion: 1
id: "9"
mappingDefinitions:
  DESTINATION:
    database: BEN_EDW
    schema: PQA_MAIN_ENV
  MULTISOURCE:
    database: COALESCE_SAMPLE_DATABASE
    schema: RAINFOREST_SAMPLE
  NEW_LOCATION:
    database: BEN_EDW
    schema: TRASH_ENV
  PRESYNC:
    database: BEN_EDW
    schema: PQA_MAIN_ENV
  SOURCE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  UNMAPPED_LOCATION:
    database: BEN_EDW
    schema: TRASH_ENV
name: Main Environment
type: Environment
